/**
 * T-AI-326 — MCP / service-first boundary for YiACAD review-assist surface.
 *
 * Defines tool contracts for:
 *   - EDA worker invocation
 *   - Parts search
 *   - CI trigger
 *   - Artifact fetch
 *   - Review hints (read-only)
 *
 * All tools are READ-ONLY from the agent perspective. Write operations
 * (commit, merge, ERC fix) remain exclusively in the human operator path.
 */

// ---------------------------------------------------------------------------
// Shared types
// ---------------------------------------------------------------------------

export interface McpToolResult<T = unknown> {
  ok: boolean;
  data?: T;
  error?: string;
}

// ---------------------------------------------------------------------------
// EDA Worker tool
// ---------------------------------------------------------------------------

export type EdaJobKind = "erc" | "drc" | "bom" | "gerber" | "step";

export interface EdaJobRequest {
  kind: EdaJobKind;
  schematicPath: string;
  /** Optional ref (branch/commit) — defaults to HEAD */
  gitRef?: string;
}

export interface EdaJobResult {
  jobId: string;
  status: "queued" | "running" | "done" | "failed";
  violationCount?: number;
  artifactUrl?: string;
}

export async function enqueueEdaJob(
  req: EdaJobRequest,
): Promise<McpToolResult<EdaJobResult>> {
  try {
    const res = await fetch("/api/eda/enqueue", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(req),
    });
    if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
    return { ok: true, data: (await res.json()) as EdaJobResult };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}

// ---------------------------------------------------------------------------
// Parts search tool (read-only)
// ---------------------------------------------------------------------------

export interface PartsSearchQuery {
  query: string;
  category?: string;
  maxResults?: number;
}

export interface PartResult {
  mpn: string;
  manufacturer: string;
  description: string;
  datasheet?: string;
  stock?: number;
}

export async function searchParts(
  q: PartsSearchQuery,
): Promise<McpToolResult<PartResult[]>> {
  const params = new URLSearchParams({ q: q.query });
  if (q.category) params.set("category", q.category);
  if (q.maxResults) params.set("limit", String(q.maxResults));
  try {
    const res = await fetch(`/api/parts/search?${params}`);
    if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
    return { ok: true, data: (await res.json()) as PartResult[] };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}

// ---------------------------------------------------------------------------
// CI trigger tool
// ---------------------------------------------------------------------------

export interface CiTriggerRequest {
  workflow: "firmware" | "erc" | "drc" | "full";
  gitRef?: string;
}

export interface CiRunRef {
  runId: string;
  url: string;
  status: "pending" | "running" | "success" | "failure";
}

export async function triggerCi(
  req: CiTriggerRequest,
): Promise<McpToolResult<CiRunRef>> {
  try {
    const res = await fetch("/api/ci/trigger", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(req),
    });
    if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
    return { ok: true, data: (await res.json()) as CiRunRef };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}

// ---------------------------------------------------------------------------
// Artifact fetch tool (read-only)
// ---------------------------------------------------------------------------

export interface ArtifactRef {
  kind: "gerber" | "bom" | "step" | "report";
  jobId: string;
}

export async function fetchArtifactUrl(
  ref: ArtifactRef,
): Promise<McpToolResult<{ url: string; contentType: string }>> {
  try {
    const res = await fetch(`/api/artifacts/${ref.kind}/${ref.jobId}`);
    if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
    return { ok: true, data: (await res.json()) as { url: string; contentType: string } };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}

// ---------------------------------------------------------------------------
// Review hints (read-only, generated by intelligence overlay)
// ---------------------------------------------------------------------------

export interface ReviewHint {
  severity: "error" | "warning" | "info";
  component?: string;
  message: string;
  source: "erc" | "drc" | "bom" | "agent";
}

export async function getReviewHints(
  schematicPath: string,
): Promise<McpToolResult<ReviewHint[]>> {
  try {
    const res = await fetch(
      `/api/review/hints?path=${encodeURIComponent(schematicPath)}`,
    );
    if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
    return { ok: true, data: (await res.json()) as ReviewHint[] };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}
