; PlatformIO Project Configuration
; https://docs.platformio.org/page/projectconf.html
;
; Uncomment and adapt the environment for your target board.

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; lib_deps =

; [env:nucleo_f446re]
; platform = ststm32
; board = nucleo_f446re
; framework = stm32cube
; monitor_speed = 115200
